baseURL = 'https://cq.acogdev.com/'
languageCode = 'en-us'
title = 'Color Quick'

SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true

theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]


[markup.highlight]
noclasses = false
style = "github"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
favicon = ""
site_logo = "/images/logo.webp"
description = "Your local full service printer"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-light-red"
recent_posts_number = 0

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"